import { NextRequest, NextResponse } from "next/server";

/**
 * Lightweight server-only endpoint that mirrors a single page-open event for
 * /conf into the Airtable QR-tracking table.
 *
 * Privacy: we deliberately do NOT read or persist the client IP. We only
 * forward what the browser supplied (UA, referrer, language) plus a stable
 * visitor_id and a per-open scan_id generated by the client.
 *
 * Failure mode: tracking failures never block the UX. The route returns
 * { ok: true } even on Airtable error so the client can stay fire-and-forget;
 * any error is fully logged server-side so production issues are visible in
 * logs (no silent suppression).
 */

const BASE_ID = process.env.QUOTE_BASE_ID;
const TABLE_ID = process.env.AIRTABLE_QR_TRACKING_TABLE;
const API_TOKEN = process.env.API_TOKEN;

const PAGE_VALUE = "/conf";
const CAMPAIGN_VALUE = "ggate26";
const SOURCE_VALUE = "conf_qr";
const SOURCE_LABEL_VALUE = "GGATE26 QR / CBDO Back";
const MAX_STRING_LEN = 500;
const TIMEOUT_MS = 8000;

interface TrackingPayload {
  visitorId?: string;
  scanId?: string;
  isUniqueVisitor?: boolean;
  userAgent?: string;
  referrer?: string;
  language?: string;
}

const trimString = (value: unknown, max = MAX_STRING_LEN): string => {
  if (typeof value !== "string") return "";
  const trimmed = value.trim();
  return trimmed.length > max ? trimmed.slice(0, max) : trimmed;
};

const fetchWithTimeout = async (
  url: string,
  init: RequestInit,
  timeoutMs = TIMEOUT_MS
) => {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timer);
  }
};

export async function POST(request: NextRequest) {
  if (!API_TOKEN || !BASE_ID || !TABLE_ID) {
    // Loud during dev so misconfiguration surfaces quickly, but the client
    // still gets an "ok" so the page renders normally.
    console.error("[conf-tracking] missing env config", {
      hasApiToken: Boolean(API_TOKEN),
      hasBaseId: Boolean(BASE_ID),
      hasTableId: Boolean(TABLE_ID),
    });
    return NextResponse.json({ ok: true, skipped: "config" });
  }

  let body: TrackingPayload;
  try {
    body = (await request.json()) as TrackingPayload;
  } catch (error) {
    console.warn("[conf-tracking] invalid json body", error);
    return NextResponse.json({ ok: true, skipped: "bad_body" });
  }

  const fields: Record<string, string | boolean> = {
    Timestamp: new Date().toISOString(),
    Page: PAGE_VALUE,
    Campaign: CAMPAIGN_VALUE,
    Source: SOURCE_VALUE,
    "Source Label": SOURCE_LABEL_VALUE,
    "Visitor ID": trimString(body.visitorId, 128),
    "Scan ID": trimString(body.scanId, 128),
    "User Agent": trimString(body.userAgent, 500),
    Referrer: trimString(body.referrer, 500),
    Language: trimString(body.language, 16),
    "Is Unique Visitor":
      typeof body.isUniqueVisitor === "boolean" ? body.isUniqueVisitor : true,
  };

  const url = `https://api.airtable.com/v0/${BASE_ID}/${encodeURIComponent(
    TABLE_ID
  )}`;

  const postRecord = (payload: Record<string, string | boolean>) =>
    fetchWithTimeout(url, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${API_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ fields: payload, typecast: true }),
    });

  try {
    let response = await postRecord(fields);
    if (!response.ok) {
      const errorText = await response.text();
      // Try once more with only the known-safe core fields in case the user's
      // Airtable schema is partial. Tracking failure should never break the
      // page, but we surface the original error in logs.
      console.error("[conf-tracking] airtable create failed (attempt 1)", {
        status: response.status,
        details: errorText,
        sentFields: fields,
      });

      const minimal: Record<string, string | boolean> = {
        Timestamp: fields.Timestamp,
        Page: fields.Page,
        Campaign: fields.Campaign,
        Source: fields.Source,
      };
      response = await postRecord(minimal);
      if (!response.ok) {
        const fallbackError = await response.text();
        console.error(
          "[conf-tracking] airtable create failed (fallback)",
          {
            status: response.status,
            details: fallbackError,
            sentFields: minimal,
          }
        );
        return NextResponse.json({ ok: true, skipped: "airtable_error" });
      }
    }
    return NextResponse.json({ ok: true });
  } catch (error) {
    console.error("[conf-tracking] unexpected error", error);
    return NextResponse.json({ ok: true, skipped: "exception" });
  }
}
